# ===== Builder Stage =====
FROM rust:bookworm as builder

# Set the working dir
WORKDIR /usr/src/app

# Install system dependencies required for SQLx, Postgres, and Node.js
RUN apt-get update && apt-get install -y \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install watchexec-cli

# Set env variables for nvm and node.js
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 20.18.1

# Install nvm and node.js
RUN mkdir -p $NVM_DIR \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION

# Update path so that nvm and node are available
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# Copy package.json
COPY package.json .

# Install npm deps
RUN npm install

# Copy the Cargo.toml
COPY Cargo.toml build.rs tailwind.config.js postcss.config.js .

# Expose the port your application runs on (e.g., 8080)
EXPOSE ${SERVER_PORT}

# Set the entrypoint
CMD ["watchexec", "-w", "src", "--restart", "cargo", "run"]
